### PR TITLE
Document TomEE container.

### PR DESCRIPTION
**Pull request by violetagg**

### CODE REVIEW

**Comment by nebhale** [comment]
@violetagg Looks great.  One thing I'd double check is exactly what the tags are that come out of the container.  I'm pretty sure at least one of them (the `-instance`) is different than what is currently documented.

**Comment by nebhale** [comment]
@violetagg I've merged the change to the instance, so you can update the tags in this documentation and I'll merge it.

**Comment by violetagg** [comment]
Hi,

It's already updated "<tt>tomee-instance=&lang;version&rang;</tt>" 
Do I need to update anything else?

Thanks,
Violeta

**Comment by nebhale** [comment]
Nope, I just missed the update.

**Pull request closed without merging**
